### ISSUE TITLE
iconfig: reconfigure area detector

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/bluesky_training#260]
Following development work for XPCS, refactor such as this example:

```yaml
BLUESKY_FILES_ROOT: &BLUESKY_DATA_ROOT "/home/8ididata/"
AD_IMAGE_DIR: "2023-2/pvaccess_test"
AREA_DETECTOR:
  ADSIM_4M:
    # IOC host: bixbite
    # /net/s8iddserv/xorApps/epics/synApps_6_2_1/ioc/8idSimDetectors/iocBoot/ioc8idSimDetector4m/softioc/8idSimDetector4m.pl start
    IOC_FILES_ROOT: *BLUESKY_DATA_ROOT
    NAME: adsim4M
    PV_PREFIX: "8idSimDetector4m:"
```

**Comment by prjemian** [comment]
Looking at guarneri to refactor how devices are declared.

**Comment by prjemian** [comment]
example:

```yaml
apstools.devices.ad_creator:

  - name: adsimk
    prefix: "kad:"
    labels: ["area_detector", "detectors"]
    plugins:
      - cam:
          class: apstools.devices.SimDetectorCam_V34
      - image
      - pva
      - hdf1:
          class: apstools.devices.AD_EpicsFileNameHDF5Plugin
          read_path_template: "/mnt/iocad/tmp/"
          write_path_template: "/tmp/"
      - roi1
      - stats1
```
