### ISSUE TITLE
upload documentation artifact from CI

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/bluesky_training#274]
As done in [other projects](https://github.com/prjemian/murky/blob/815acf996bb3b2daa65f4992cc31ece537ace4df/.github/workflows/docs.yml#L66-L70), this is a useful way to review changes to the project documentation.  It deposits a Zip or .tar.gz file of the static web site built by the CI process.

```yaml
    - name: Upload Docs ZIP file as artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.REPOSITORY_NAME }}-docs
        path: docs/build/html/
```
